destroy configured

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -4,6 +4,7 @@ on:
     branches:
       - main
       - stage
+      - destroy
     paths:
       - terraform/**
   pull_request:
@@ -26,7 +27,7 @@ jobs:
     defaults:
       run:
         shell: bash
-        working-directory: ./terraform
+        #working-directory: ./terraform
 
     steps:
       - name: Checkout source code
@@ -37,32 +38,6 @@ jobs:
         with:
           terraform_version: 1.1.7
 
-      - name: Terraform init
-        id: init
-        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
-
-      - name: Terraform format
-        id: fmt
-        run: terraform fmt -check
-
-      - name: Terraform validate
-        id: validate
-        run: terraform validate
-
-      - name: Terraform plan
-        id: plan
-        run: terraform plan -no-color -input=false -out planfile
-        continue-on-error: true
-
-      - name: Terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-
-      - name: Terraform Apply
-        id: apply
-        if: github.ref == 'refs/heads/main' && github.event_name =='push'
-        run: terraform apply --auto-approve -input=false -parallelism=1 planfile
-
       - name: Congigure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
@@ -70,12 +45,60 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
 
-      - name: Get kube config file
-        id: getkubeconfig
-        if: steps.apply.outcome == 'success'
-        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}
+      - name: Delete Cluster
+        id: delete-cluster
+        if: github.ref == 'refs/heads/destroy' && github.event_name =='push'
+        run: kubectl delete -f  https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/cloud/deploy.yml
 
-      - name: Install Ingress Controller
-        id: ingress
-        if: steps.apply.outcome == 'success' && steps.getkubeconfig.outcome == 'sucsess'
-        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/cloud/deploy.yml
+      - name: Terraform Init
+        id: init
+        if: github.ref == 'refs/heads/destroy' && github.event_name =='push'
+        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
+
+      - name: Terraform Destroy
+        id: destroy
+        if: github.ref == 'refs/heads/destroy' && github.event_name =='push'
+        run: terraform destroy --auto-approve
+
+      # - name: Terraform init
+      #   id: init
+      #   run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
+
+      # - name: Terraform format
+      #   id: fmt
+      #   run: terraform fmt -check
+
+      # - name: Terraform validate
+      #   id: validate
+      #   run: terraform validate
+
+      # - name: Terraform plan
+      #   id: plan
+      #   run: terraform plan -no-color -input=false -out planfile
+      #   continue-on-error: true
+
+      # - name: Terraform plan status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
+
+      # - name: Terraform Apply
+      #   id: apply
+      #   if: github.ref == 'refs/heads/main' && github.event_name =='push'
+      #   run: terraform apply --auto-approve -input=false -parallelism=1 planfile
+
+      # - name: Congigure AWS Credentials
+      #   uses: aws-actions/configure-aws-credentials@v4
+      #   with:
+      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      #     aws-region: ${{ env.AWS_REGION }}
+
+      # - name: Get kube config file
+      #   id: getkubeconfig
+      #   if: steps.apply.outcome == 'success'
+      #   run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}
+
+      # - name: Install Ingress Controller
+      #   id: ingress
+      #   if: steps.apply.outcome == 'success' && steps.getkubeconfig.outcome == 'sucsess'
+      #   run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/cloud/deploy.yml
