delete

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -49,19 +49,19 @@ jobs:
         id: validate
         run: terraform validate
 
-      - name: Terraform plan
-        id: plan
-        run: terraform plan -no-color -input=false -out planfile
-        continue-on-error: true
+      # - name: Terraform plan
+      #   id: plan
+      #   run: terraform plan -no-color -input=false -out planfile
+      #   continue-on-error: true
 
-      - name: Terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform plan status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
-      - name: Terraform Apply
-        id: apply
-        if: github.ref == 'refs/heads/main' && github.event_name =='push'
-        run: terraform apply --auto-approve -input=false -parallelism=1 planfile
+      # - name: Terraform Apply
+      #   id: apply
+      #   if: github.ref == 'refs/heads/main' && github.event_name =='push'
+      #   run: terraform apply --auto-approve -input=false -parallelism=1 planfile
 
       - name: Congigure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
